import './globals.css';
import StoryblokProvider from '@/components/StoryblokProvider';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<StoryblokProvider>
			<html lang="en">
				<body className="bg-linear-to-b from-amber-50 to-stone-200 text-gray-800 mx-auto">
					<Header />
					<div className="max-w-3xl mx-auto">{children}</div>
					<Footer />
				</body>
			</html>
		</StoryblokProvider>
	);
}
